# Site Configuration
lang: en
timezone: Europe/Berlin

title: Fauzan Arif
tagline: On a quest to explore Data Science.
description: A seasoned Data Recruiter turned Data Professional with study background in quantitative areas of Finance and Economics. On a quest to explore Data Science.
url: ""

social_links:
  LinkedIn: https://linkedin.com/in/fauzan-arif
  Github:   https://github.com/fauzan-arif


collections:
  portfolio:
    output: true
    permalink: /works/:path/

navigation:
  - title: About
    url: /about
  
  - title: Portfolio
    url: /portfolio

  - title: Contact
    url: /contact

plugins:
  - jekyll-octicons